name: 🚀 Deploy to VPS on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🔄 Deploy on VPS
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🔐 Install SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github_deploy
          chmod 600 ~/.ssh/id_rsa_github_deploy
          ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts

      - name: 🚀 Connect and Pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
